service: ffoi

provider:
  name: aws
  runtime: nodejs6.10
  role: ${env:FFOI_SLS_LAMBA_ROLE}
  stage: ${env:FFOI_TARGET_ENV_NAME}
  region: ${env:FFOI_TARGET_REGION}
  deploymentBucket:
    name: ${env:FFOI_SLS_BUCKET}
package:
 exclude:
   - test
functions:
  process:
    handler: lib/functions/process.process
    timeout: 30
    # events:
    #   - s3:
    #       bucket: ${env:FFOI_SLS_BUCKET}
    #       event: s3:ObjectCreated:*
    #       rules:
    #         - prefix: ffoi/
    #         - suffix: .XML